services:
  - type: web
    name: pet-grooming-services-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_SSL
        value: "true"
      - key: DB_SSL_REJECT_UNAUTHORIZED
        value: "false"
      - key: SESSION_SECRET
        sync: false
      - key: FE_ORIGIN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false
